# -*- coding: utf-8 -*-
"""Monitoramento

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZQi2hr6oGMzipxnwf6LuhLEzcryrql9-

#*Monitoramento*

Bibliotecas
"""

# Instalação rápida caso o ambiente tenha sido reiniciado
try:
    import ultralytics
except:
    !pip install ultralytics -q

import cv2
import numpy as np
from ultralytics import YOLO
from IPython.display import display, Javascript, HTML
from google.colab.output import eval_js
from base64 import b64decode, b64encode
import time

# 1. Carrega o modelo de IA
print("⏳ Carregando Inteligência Artificial...")
modelo = YOLO('yolov8n.pt')
print("✅ IA Pronta. Iniciando sensor de visão...")

# 2. Código JavaScript para abrir a câmera e gerenciar o fluxo de imagens no navegador
js_streaming = """
var video;
var canvas;
var imgElement;
var stream;

async function iniciarCamera() {
    const div = document.createElement('div');
    div.style.position = 'relative';
    div.style.width = '640px';
    div.style.height = '480px';
    document.body.appendChild(div);

    video = document.createElement('video');
    video.style.display = 'none'; // Escondemos o vídeo original
    stream = await navigator.mediaDevices.getUserMedia({video: {width: 640, height: 480}});
    video.srcObject = stream;
    await video.play();

    // Este canvas captura a foto
    canvas = document.createElement('canvas');
    canvas.width = 640;
    canvas.height = 480;

    // Esta imagem mostra o resultado da IA
    imgElement = document.createElement('img');
    imgElement.style.position = 'absolute';
    imgElement.style.top = '0';
    imgElement.style.left = '0';
    imgElement.style.width = '640px';
    imgElement.style.height = '480px';
    div.appendChild(imgElement);

    // Botão de parada de emergência
    const btn = document.createElement('button');
    btn.textContent = '🛑 PARAR MONITORAMENTO';
    btn.style.position = 'absolute';
    btn.style.zIndex = '100';
    btn.onclick = () => { window.pararIA = true; stream.getVideoTracks()[0].stop(); div.remove(); };
    document.body.appendChild(btn);

    window.pararIA = false;
}

// Função para tirar um quadro (frame) atual do vídeo
async function capturarQuadro() {
    if (window.pararIA) return "PARAR";
    canvas.getContext('2d').drawImage(video, 0, 0, 640, 480);
    return canvas.toDataURL('image/jpeg', 0.8);
}

// Função para atualizar a tela com o resultado da IA
function mostrarResultado(base64Image) {
    if (!window.pararIA) {
        imgElement.src = 'data:image/jpeg;base64,' + base64Image;
    }
}
"""

# Injeta o JS e liga a câmera
display(Javascript(js_streaming))
eval_js('iniciarCamera()')

# 3. LOOP DE MONITORAMENTO CONTÍNUO (O coração da Indústria 4.0)
# Vamos processar quadro a quadro até o operador clicar em PARAR
while True:
    # Tenta pegar um quadro do navegador
    try:
        quadro_b64 = eval_js('capturarQuadro()')
    except:
        break

    if quadro_b64 == "PARAR":
        print("🛑 Inspeção interrompida pelo operador.")
        break

    # Se pegou o quadro, converte de base64 para imagem OpenCV (matriz)
    bytes_imagem = b64decode(quadro_b64.split(',')[1])
    array_numpy = np.frombuffer(bytes_imagem, dtype=np.uint8)
    frame = cv2.imdecode(array_numpy, cv2.IMREAD_COLOR)

    # 4. INFERÊNCIA DA IA (Detecção)
    # verbose=False para não poluir o terminal, conf=0.5 para precisão mínima de 50%
    resultados = modelo.predict(source=frame, conf=0.5, verbose=False)

    # 5. RENDERIZAÇÃO
    frame_anotado = resultados[0].plot() # O YOLO desenha as caixas

    # Adiciona a contagem de peças no HUD da tela
    contagem = len(resultados[0].boxes)
    cv2.rectangle(frame_anotado, (10, 10), (350, 50), (0, 0, 0), -1)
    cv2.putText(frame_anotado, f"Itens detectados: {contagem}", (20, 35), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 0), 2)

    # Converte o frame anotado de volta para base64 para o navegador exibir
    _, buffer = cv2.imencode('.jpg', frame_anotado)
    resultado_b64 = b64encode(buffer).decode('utf-8')

    # Envia de volta para a tela do aluno
    eval_js(f'mostrarResultado("{resultado_b64}")')